stages:
  - test
  - build
  - deploy

docker_build:
  stage: build
  environment: prod
  only:
    - main
  tags:
    - build
    - docker
  script:
    # create .env file
    - echo "NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL" >> .env
    - echo "NODE_ENV=$NODE_ENV" >> .env
    - echo "NEXTAUTH_URL=$NEXTAUTH_URL" >> .env
    - echo "NEXTAUTH_SECRET=$NEXTAUTH_SECRET" >> .env
    - echo "KEYCLOAK_ID=$KEYCLOAK_ID" >> .env
    - echo "KEYCLOAK_SECRET=$KEYCLOAK_SECRET" >> .env
    - echo "KEYCLOAK_ISSUER=$KEYCLOAK_ISSUER" >> .env
    - echo "NEXT_PUBLIC_TINY_MCE=$NEXT_PUBLIC_TINY_MCE" >> .env
    - echo "PAGE_INIT_LATTE=$PAGE_INIT_LATTE" >> .env
    - echo DATE_VERSION=$(date +%d-%m-%Y) >> .env

    # perform login on docker registry
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

    # build project images
    - docker compose -f docker-compose.build.yml build

    # push project images to registry
    - docker compose -f docker-compose.build.yml push

    - docker system prune -f

docker_up:
  stage: deploy
  environment: prod
  only:
    - main
  tags:
    - ssh
    - prod
  script:
    # create .env file
    - echo "NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL" >> .env
    - echo "NODE_ENV=$NODE_ENV" >> .env
    - echo "NEXTAUTH_URL=$NEXTAUTH_URL" >> .env
    - echo "NEXTAUTH_SECRET=$NEXTAUTH_SECRET" >> .env
    - echo "KEYCLOAK_ID=$KEYCLOAK_ID" >> .env
    - echo "KEYCLOAK_SECRET=$KEYCLOAK_SECRET" >> .env
    - echo "KEYCLOAK_ISSUER=$KEYCLOAK_ISSUER" >> .env
    - echo "NEXT_PUBLIC_TINY_MCE=$NEXT_PUBLIC_TINY_MCE" >> .env
    - echo "PAGE_INIT_LATTE=$PAGE_INIT_LATTE" >> .env
    - echo "DOMAIN_APPLICATION=$DOMAIN_APPLICATION" >> .env
    - echo "SENTRY_DNS=$SENTRY_DNS" >> .env

    # perform login on docker registry
    - docker login $CI_REGISTRY

    - docker compose pull

    - docker stack deploy -c <(docker compose -f docker-compose.yml config | tail -n +2) meu_bolsista --with-registry-auth

    - docker system prune -f
