version: "3.9"
services:
  meu_bolsista_front:
    container_name: meu_bolsista_front
    build:
      context: ./
      dockerfile: docker/Dockerfile
    image: registry.gitlab.alverad.com.br/meu-bolsista/meu_bolsista_front
    restart: always
    networks:
      - traefik-public
    deploy:
      placement:
        constraints:
          - node.labels.service == front
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik-public"
        - "traefik.constraint-label=traefik-public"

        - "traefik.http.routers.meu_bolsista_front.rule=Host(`${DOMAIN_APPLICATION}`)"
        - "traefik.http.routers.meu_bolsista_front.entrypoints=http"
        - "traefik.http.routers.meu_bolsista_front.middlewares=https-redirect@file"

        - "traefik.http.routers.meu_bolsista_front_https.rule=Host(`${DOMAIN_APPLICATION}`)"
        - "traefik.http.routers.meu_bolsista_front_https.entrypoints=https"
        - "traefik.http.routers.meu_bolsista_front_https.tls=true"
        - "traefik.http.routers.meu_bolsista_front_https.tls.certresolver=le"
        - "traefik.http.routers.meu_bolsista_front_https.middlewares=default-headers@file"
        - "traefik.http.services.meu_bolsista_front_https.loadbalancer.server.port=80"

networks:
  traefik-public:
    external: true
