version: "3.3"
services:
  meu_bolsista_front:
    container_name: meu_bolsista_front
    build:
      context: ./
      dockerfile: docker/Dockerfile
    image: registry.gitlab.com/meu-bolsista/meu_bolsista_front
    env_file:
      - .env
    restart: always
    command: npm run start
    ports:
      - 4000:80
