
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


function Layout({ children, modal }: { children: React.ReactNode; modal: React.ReactNode; }) {
  return (
    <>
      {children}
      {modal}
    </>
  );
};
export default Layout;
