import FlowbiteContext from '@/context/FlowbiteContext'
import { Inter } from 'next/font/google'
import { FC, PropsWithChildren } from 'react'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const RootLayout: FC<PropsWithChildren> = function ({ children }) {
  return (
    <html lang="pt-BR">
      <body className='flex h-screen w-full flex-col overflow-hidden'>
        <FlowbiteContext>{children}</FlowbiteContext>
      </body>
    </html>
  );
};
export default RootLayout;
