import { AuthProvider } from '@/context/AuthenticateContext';
import FlowbiteContext from '@/context/FlowbiteContext';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


function RootLayout({ children }: { children: React.ReactNode; }) {
  return (
    <html lang="pt-BR">
      <body className='flex h-screen w-full flex-col overflow-hidden'>
        <AuthProvider>
          <FlowbiteContext>{children}</FlowbiteContext>
        </AuthProvider>
      </body>
    </html>
  );
};
export default RootLayout;
