import { AuthProvider } from "@/context/AuthenticateContext"
import FlowbiteContext from "@/context/FlowbiteContext"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='flex h-screen w-full flex-col overflow-hidden'>
        <AuthProvider>
          <FlowbiteContext>{children}</FlowbiteContext>
        </AuthProvider>
      </body>
    </html>
  )
}
