
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


function Layout({ children }: { children: React.ReactNode }) {
  return (
    <>
      {children}
    </>
  );
};
export default Layout;
